In [7]:
import torch
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])

In [9]:
points[4]

tensor(3.)

In [23]:
conda env list


# conda environments:
#
# * -> active
# + -> frozen
base                     /opt/anaconda3
bookenv                  /opt/anaconda3/envs/bookenv
mastering-pytorch    *   /opt/anaconda3/envs/mastering-pytorch


Note: you may need to restart the kernel to use updated packages.


In [26]:
points.shape

torch.Size([3, 2])

In [57]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]], device='mps')
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=mps:0) of size 6]

In [40]:
points[0, 1].storage_offset()

1

In [41]:
points.size()

torch.Size([3, 2])

In [47]:
points.stride()

(2, 1)

In [43]:
points.storage_offset()

0

In [46]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]], device='mps:0')

In [45]:
points[2].storage_offset()

4

In [50]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float64)
points

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [5]:
import torch
print(torch.backends.mps.is_available())   # Should be True for Apple Silicon

True


In [12]:
# Move an existing tensor to MPS
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
gpu_points = points.to('mps')

# Or create it directly on MPS
gpu_points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0], device='mps')

In [13]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
print(points)

tensor([1., 4., 2., 1., 3., 5.])


In [6]:
points.stride()

(1,)

In [32]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float64)
print(points)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [44]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]], device='mps')
print(points)

tensor([[1., 2.],
        [3., 4.]], device='mps:0')


In [45]:
torch.__version__

'2.5.1'

In [59]:
## torch.utils.data

from torch.utils.data import (TensorDataset, DataLoader)

In [65]:

import torch
from torch.utils.data import TensorDataset, DataLoader

# Define your training data
x_train = torch.randn(100, 10)   # 100 samples, 10 features
y_train = torch.randint(0, 2, (100,))  # 100 binary labels

train_dataset = TensorDataset(x_train, y_train)
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)



In [ ]:
for x_batch in train_dataloader:
    x_batch, y_batch = batch
    print(x_batch.shape, y_batch.shape)
    break  # Just show the first batch

torch.Size([32, 10]) torch.Size([32])
